language: python

python:
  - "3.7"

install:
  - "pip install pipenv"
  - "pip install codecov"
  - "pipenv sync"

script: "python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests"

after_success:
  - codecov
